name: lando-website
services:
  node:
    type: node:14
    build:
      - yarn install
    scanner: false
    ssl: false
    sslExpose: false
    overrides:
      ports:
        - 8010:8010
tooling:
  node:
    service: node
  yarn:
    service: node
  dev:
    service: node
    cmd: yarn dev --port 8010
