[build]
  base = "./"
  publish = "_site"
  command = "yarn build"

# Domain redirects
[[redirects]]
  from = "https://devwithlando.io/*"
  to = "https://lando.dev/:splat"
  status = 301
[[redirects]]
  from = "https://lndo.io/*"
  to = "https://lando.dev/:splat"
  status = 301

  # Legacy redirects from cloudflare
[[redirects]]
  from = "https://lando.dev/sponsor/"
  to = "https://github.com/sponsors/lando"
  status = 301
[[redirects]]
  from = "https://lando.dev/join/"
  to = "https://docs.lando.dev/contrib/contributing.html"
  status = 301
[[redirects]]
  from = "https://lando.dev/alliance/join/"
  to = "https://docs.lando.dev/contrib/contributing.html"
  status = 301

# Subsite redirects
[[redirects]]
  from = "/blog/*"
  to = "https://lando-blog.netlify.app/blog/:splat"
  status = 200
  force = true
